### ISSUE TITLE
Parse with country code "1" fails

### ISSUE THREAD

**Issue by JamesHancockAtteria** [TrevorPilley/phone-number-parser#608]
If you pass a north american phone number and "1" as the country code it fails saying that it isn't supported. If you pass it as +1{number} it works.

Also it doesn't support "001" which is the real country code nor "044" etc. It should be able to handle the fully padded version and the simple version, and the parse function should acccept "1" or "001" as a value.

**Comment by TrevorPilley** [comment]
Hi James,

The input to `PhoneNumber.Parse(string)` can be in any of the following standard formats:

- E.164 format: `+441142726444`
- E.123 international format: `+44 114 272 6444`
- RFC3966 format: `tel:+44-114-272-644`

If the phone number is in a national format for example `(0114) 272 6444`, then either:

- The country must be specified by calling `PhoneNumber.Parse(string, CountryInfo)’
- `PhoneNumber.TryParse(string, out IEnumerable<PhoneNumber>)` must be used which may return multiple countries if the number would be valid for more than one country

Country codes don’t have any leading zeros, for example the country code for the UK is `44` and the country code for the US is `1`. Where you might see something like `0044` the `00` represents the international dialling code (to dial internationally) and related to the country _you are dialling from_ and therefore isn’t actually portable because not all countries use the ITU recommended value of `00`. The `+` character indicates that the caller’s telephony provider substitute the relevant IDC and in some cases a carrier selection code to make the call.

This number for example `+441142726444` if represented as `00441142726444` could not be dialled from a US phone, there it would need representing as `011441142726444`.

I hope that clarifies it for you.

Trev

**Comment by TrevorPilley** [comment]
>If you pass a north american phone number and "1" as the country code it fails saying that it isn't supported. If you pass it as +1{number} it works.

Are you referring to something like this `PhoneNumber.Parse(“2124841200”, “1”)`?

If so, the country code string refers to the ISO 3166 Alpha-2 country code, not the calling code so `PhoneNumber.Parse(“2124841200”, ”US”)` would be how that should be provided.

If that’s not clear from the readme or XML comments in the library, please let me know where that would need clarifying.
